#!/usr/bin/env bash
# =============================================================
#  MoneyFlow — Build Tool
#  Package : co.tpcreative.moneyflow.app
#  Firebase : moneyflow-ddc15
# =============================================================
set -euo pipefail

PACKAGE_NAME="co.tpcreative.moneyflow.app"
IOS_BUNDLE_ID="co.tpcreative.moneyflow.app"
FIREBASE_PROJECT_ID="moneyflow-ddc15"
COMPILE_SDK=36
TARGET_SDK=36
MIN_SDK=21
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

# ── Android SDK / AVD paths ───────────────────────────────────
# Point to your custom AVD folder so Flutter and the emulator
# tool use YOUR avd directory instead of ~/.android/avd
export ANDROID_AVD_HOME="/Users/phong070/Documents/AndroidSDK/avd"
# Also set SDK root if not already set in your shell profile
export ANDROID_HOME="${ANDROID_HOME:-/Users/phong070/Documents/AndroidSDK}"
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-/Users/phong070/Documents/AndroidSDK}"

# ── Cross-platform sed in-place ───────────────────────────────
# macOS uses BSD sed (sed -i ''), Linux uses GNU sed (sed -i)
if [[ "$(uname)" == "Darwin" ]]; then
  _sed_i() { sed -i '' "$@"; }
else
  _sed_i() { sed -i "$@"; }
fi

# ── Colours ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

ok()   { echo -e "  ${GREEN}✔${RESET}  $*"; }
warn() { echo -e "  ${YELLOW}⚠${RESET}  $*"; }
err()  { echo -e "  ${RED}✘${RESET}  $*"; exit 1; }
info() { echo -e "  ${CYAN}›${RESET}  $*"; }
hdr()  { echo -e "\n  ${BOLD}── $* ──────────────────────────────────────────────${RESET}"; }

# ── Banner ───────────────────────────────────────────────────
show_menu() {
  clear
  echo -e "${BOLD}"
  echo "  ╔══════════════════════════════════════════════════════╗"
  echo "  ║           MoneyFlow — Build Tool                     ║"
  echo "  ║  Package : $PACKAGE_NAME               ║"
  echo "  ║  Firebase: $FIREBASE_PROJECT_ID                           ║"
  echo "  ╚══════════════════════════════════════════════════════╝"
  echo -e "${RESET}"
  echo "  ── 🤖 Android ──────────────────────────────"
  echo "   1) Run Android   debug"
  echo "   2) Run Android   release"
  echo "   3) Build Android release APK + AAB"
  echo ""
  echo "  ── 🍎 iOS ───────────────────────────────────"
  echo "   4) Run iOS       debug"
  echo "   5) Run iOS       release"
  echo "   6) Build iOS     release IPA"
  echo ""
  echo "  ── 🚀 Both ──────────────────────────────────"
  echo "   7) Build Android + iOS release"
  echo ""
  echo "   0) Exit"
  echo "  ──────────────────────────────────────────────"
  printf "  Select: "
}

# ── Step 1 — Check dependencies ──────────────────────────────
check_deps() {
  hdr "Step 1: Check dependencies"
  for tool in flutter git; do
    path=$(command -v "$tool" 2>/dev/null) \
      && ok "$tool  $path" \
      || err "$tool not found — please install it and re-run."
  done
}

# ── Step 2 — Flutter clean + pub get ─────────────────────────
flutter_clean_get() {
  hdr "Step 2: Flutter clean & pub get"
  cd "$PROJECT_DIR"
  info "flutter clean"
  flutter clean
  info "flutter pub get"
  flutter pub get
  ok "Flutter ready"
}

# ── Step 3a — Write android/settings.gradle.kts ──────────────
# FIX: Modern Flutter (3.x+) uses the new plugin management DSL
# in settings.gradle.kts. The google-services plugin MUST be
# declared here — NOT in a buildscript{} block in build.gradle.kts.
# Mixing both approaches causes "BUILD FAILED" (assembleDebug exit 1).
write_settings_gradle() {
  local SETTINGS="$PROJECT_DIR/android/settings.gradle.kts"
  mkdir -p "$(dirname "$SETTINGS")"

  # Read the Flutter SDK path from local.properties (already generated by Flutter)
  local LOCAL_PROPS="$PROJECT_DIR/android/local.properties"
  if [[ ! -f "$LOCAL_PROPS" ]]; then
    warn "android/local.properties not found — run 'flutter pub get' first, then retry."
  fi

  cat > "$SETTINGS" <<'EOF'
pluginManagement {
    val flutterSdkPath = run {
        val properties = java.util.Properties()
        file("local.properties").inputStream().use { properties.load(it) }
        val flutterSdkPath = properties.getProperty("flutter.sdk")
        require(flutterSdkPath != null) { "flutter.sdk not set in local.properties" }
        flutterSdkPath
    }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "8.11.1" apply false   // bumped: 8.7.0 → 8.11.1
    // Google Services plugin declared here (new plugin DSL — not buildscript{} classpath)
    id("com.google.gms.google-services") version "4.4.2" apply false
    id("org.jetbrains.kotlin.android") version "2.2.20" apply false  // bumped: 2.1.0 → 2.2.20
}

include(":app")
EOF
  ok "Written android/settings.gradle.kts (AGP=8.11.1, Kotlin=2.2.20, google-services=4.4.2)"
}

# ── Step 3b — Write android/build.gradle.kts (root) ─────────
# FIX: NO buildscript{} block here. In the new plugin DSL, the
# google-services classpath lived in buildscript{} — but that
# conflicts with settings.gradle.kts plugin management and is
# the direct cause of the assembleDebug BUILD FAILED error.
write_root_gradle() {
  local ROOT_GRADLE="$PROJECT_DIR/android/build.gradle.kts"
  mkdir -p "$(dirname "$ROOT_GRADLE")"
  cat > "$ROOT_GRADLE" <<'EOF'
// Root build.gradle.kts — plugin declarations are in settings.gradle.kts
// Do NOT add a buildscript{} block here; it conflicts with the plugin DSL.

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
EOF
  ok "Written android/build.gradle.kts (root — no buildscript block)"
}

# ── Step 3c — Write android/app/build.gradle.kts (app) ───────
write_app_gradle() {
  local GRADLE="$PROJECT_DIR/android/app/build.gradle.kts"
  mkdir -p "$(dirname "$GRADLE")"

  cat > "$GRADLE" <<EOF
// FIX: import required in Kotlin DSL — java.util.Properties is not auto-imported
import java.util.Properties

plugins {
    id("com.android.application")
    id("com.google.gms.google-services")      // applied here, declared in settings.gradle.kts
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "$PACKAGE_NAME"
    compileSdk = $COMPILE_SDK
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "$PACKAGE_NAME"
        minSdk = $MIN_SDK
        targetSdk = $TARGET_SDK
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    // Release signing — reads android/key.properties
    val keyPropsFile = rootProject.file("key.properties")
    if (keyPropsFile.exists()) {
        val keyProps = Properties().apply {
            load(keyPropsFile.inputStream())
        }
        signingConfigs {
            create("release") {
                storeFile     = file(keyProps["storeFile"] as String)
                storePassword = keyProps["storePassword"] as String
                keyAlias      = keyProps["keyAlias"] as String
                keyPassword   = keyProps["keyPassword"] as String
            }
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }
        release {
            signingConfig = if (keyPropsFile.exists())
                signingConfigs.getByName("release")
            else
                signingConfigs.getByName("debug")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
EOF
  ok "Written android/app/build.gradle.kts  (package=$PACKAGE_NAME, compileSdk=$COMPILE_SDK, targetSdk=$TARGET_SDK, minSdk=$MIN_SDK)"
}

# ── Step 3d — Write all three Android Gradle files ───────────
patch_android_gradle() {
  write_settings_gradle   # must come first — declares all plugins
  write_root_gradle
  write_app_gradle
}

# ── Step 3e — Read key/key.txt and write android/key.properties ──
# key/key.txt format (lines may appear in any order, extra whitespace ok):
#   Password: mobile@123
#   Alias:    mobile
# key/mobile.jks is the keystore file (stays in key/ — referenced by relative path)
setup_key_properties() {
  hdr "Step 3: Android — signing key setup"

  local KEY_DIR="$SCRIPT_DIR/key"
  local KEY_TXT="$KEY_DIR/key.txt"
  local JKS_SRC="$KEY_DIR/mobile.jks"
  local KEY_PROPS="$PROJECT_DIR/android/key.properties"

  # ── Locate key.txt ────────────────────────────────────────────
  if [[ ! -f "$KEY_TXT" ]]; then
    warn "key/key.txt not found — skipping key.properties generation"
    warn "  Release builds will fall back to the debug signing key."
    return
  fi

  # ── Locate mobile.jks ────────────────────────────────────────
  if [[ ! -f "$JKS_SRC" ]]; then
    err "key/mobile.jks not found. Expected at: $JKS_SRC"
  fi

  # ── Parse key.txt  (handles any amount of surrounding whitespace) ──
  local password="" alias_name=""
  while IFS= read -r line; do
    # Strip carriage returns (Windows line endings)
    line="${line//$'\r'/}"
    if [[ "$line" =~ ^[[:space:]]*[Pp]assword[[:space:]]*:[[:space:]]*(.+)$ ]]; then
      password="${BASH_REMATCH[1]}"
      # Trim trailing whitespace
      password="${password%"${password##*[![:space:]]}"}"
    elif [[ "$line" =~ ^[[:space:]]*[Aa]lias[[:space:]]*:[[:space:]]*(.+)$ ]]; then
      alias_name="${BASH_REMATCH[1]}"
      alias_name="${alias_name%"${alias_name##*[![:space:]]}"}"
    fi
  done < "$KEY_TXT"

  if [[ -z "$password" ]]; then
    err "Could not parse 'Password:' from key/key.txt"
  fi
  if [[ -z "$alias_name" ]]; then
    err "Could not parse 'Alias:' from key/key.txt"
  fi

  # ── storeFile path: relative from android/ to key/mobile.jks ──
  # android/key.properties is read by rootProject in android/,
  # so "../key/mobile.jks" resolves to project_root/key/mobile.jks
  local STORE_FILE="../key/mobile.jks"

  # ── Write android/key.properties ─────────────────────────────
  mkdir -p "$(dirname "$KEY_PROPS")"
  cat > "$KEY_PROPS" <<EOF
storeFile=$STORE_FILE
storePassword=$password
keyAlias=$alias_name
keyPassword=$password
EOF

  ok "Written android/key.properties"
  ok "  storeFile     → $STORE_FILE  (key/mobile.jks)"
  ok "  keyAlias      → $alias_name"
  ok "  storePassword → ${password//?/*}  (masked)"
  ok "  keyPassword   → ${password//?/*}  (masked)"

  # ── Verify the keystore is readable (keytool sanity check) ───
  if command -v keytool &>/dev/null; then
    if keytool -list \
         -keystore "$JKS_SRC" \
         -storepass "$password" \
         -alias "$alias_name" \
         &>/dev/null 2>&1; then
      ok "Keystore verified ✔  (keytool -list passed)"
    else
      warn "Keystore verification failed — check password/alias in key/key.txt"
      warn "  keytool -list -keystore $JKS_SRC -alias $alias_name"
    fi
  else
    warn "keytool not found — skipping keystore verification"
  fi
}

# ── Step 3f — Copy & validate Android platform files ─────────
copy_android_files() {
  hdr "Step 3: Android — copy platform files"

  local GS_DST="$PROJECT_DIR/android/app/google-services.json"

  # Search order: next to build.sh → google_services/ subfolder → already in place
  local GS_SRC=""
  for candidate in \
      "$SCRIPT_DIR/google-services.json" \
      "$SCRIPT_DIR/google_services/google-services.json" \
      "$GS_DST"; do
    [[ -f "$candidate" ]] && { GS_SRC="$candidate"; break; }
  done

  if [[ -z "$GS_SRC" ]]; then
    err "google-services.json not found. Looked in:
         • $SCRIPT_DIR/google-services.json
         • $SCRIPT_DIR/google_services/google-services.json
         • $GS_DST
       Download it from Firebase Console → Project Settings → Your Android app."
  fi

  if [[ "$GS_SRC" != "$GS_DST" ]]; then
    cp "$GS_SRC" "$GS_DST"
    ok "Copied google-services.json  ($GS_SRC → android/app/)"
  else
    ok "google-services.json already in place at android/app/"
  fi

  # ── Validate package_name AND Firebase project_id ────────────
  if command -v python3 &>/dev/null; then
    local found_pkg found_proj
    read -r found_pkg found_proj < <(python3 - "$GS_DST" <<'PYEOF'
import json, sys
try:
    data = json.load(open(sys.argv[1]))
    pkgs = [c["client_info"]["android_client_info"]["package_name"]
            for c in data.get("client", [])
            if "android_client_info" in c.get("client_info", {})]
    proj = data.get("project_info", {}).get("project_id", "")
    print(",".join(pkgs), proj)
except Exception as e:
    print("", "", file=sys.stderr)
    sys.exit(1)
PYEOF
    )

    # Package name check
    if [[ "$found_pkg" == *"$PACKAGE_NAME"* ]]; then
      ok "google-services.json package_name ✔ → $PACKAGE_NAME"
    else
      warn "google-services.json package_name mismatch!"
      warn "  Expected : $PACKAGE_NAME"
      warn "  Found    : ${found_pkg:-<could not parse>}"
      warn "  Download the correct file from Firebase Console → Your Android app."
    fi

    # Firebase project ID check  (FIX: was never validated before)
    if [[ "$found_proj" == "$FIREBASE_PROJECT_ID" ]]; then
      ok "google-services.json project_id ✔ → $FIREBASE_PROJECT_ID"
    else
      warn "google-services.json project_id mismatch!"
      warn "  Expected : $FIREBASE_PROJECT_ID"
      warn "  Found    : ${found_proj:-<could not parse>}"
    fi
  fi

  # ── Cross-check: iOS bundle_id embedded in google-services.json ──
  # google-services.json can optionally embed an iOS client entry under
  # appinvite_service.other_platform_oauth_client.  If that ios_info.bundle_id
  # does NOT match $IOS_BUNDLE_ID the Firebase App Invites / Dynamic Links
  # SDK on iOS will silently use the wrong client, and Google Sign-In may
  # fail at runtime.  This is a Firebase Console misconfiguration — fix it
  # there, not in the file.
  if command -v python3 &>/dev/null && [[ -f "$GS_DST" ]]; then
    local found_ios_bundle
    found_ios_bundle=$(python3 - "$GS_DST" <<'PYEOF2'
import json, sys
try:
    data = json.load(open(sys.argv[1]))
    for client in data.get("client", []):
        for oc in client.get("services", {}).get("appinvite_service", {}).get("other_platform_oauth_client", []):
            ios = oc.get("ios_info", {})
            bid = ios.get("bundle_id", "")
            if bid:
                print(bid)
                break
except Exception:
    pass
PYEOF2
    )
    if [[ -n "$found_ios_bundle" ]]; then
      if [[ "$found_ios_bundle" == "$IOS_BUNDLE_ID" ]]; then
        ok "google-services.json ios_info.bundle_id ✔ → $found_ios_bundle"
      else
        warn "google-services.json ios_info.bundle_id MISMATCH — Firebase Console misconfiguration!"
        warn "  Expected : $IOS_BUNDLE_ID"
        warn "  Found    : $found_ios_bundle"
        warn "  Fix: Firebase Console → Project Settings → Your iOS app → verify Bundle ID is $IOS_BUNDLE_ID"
        warn "  Then re-download google-services.json and replace the copy next to build.sh."
      fi
    fi
  fi

  # ── key.properties ───────────────────────────────────────────
  local KP="$PROJECT_DIR/android/key.properties"
  if [[ -f "$KP" ]]; then
    ok "android/key.properties already exists"
  else
    warn "android/key.properties missing — release signing will use debug key"
  fi
}

# ── Step 3f — Copy & validate iOS platform files ─────────────
copy_ios_files() {
  hdr "Step 3: iOS — copy platform files"

  local PLIST_DST="$PROJECT_DIR/ios/Runner/GoogleService-Info.plist"

  # Search order: next to build.sh → google_services/ subfolder → already in place
  local PLIST_SRC=""
  for candidate in \
      "$SCRIPT_DIR/GoogleService-Info.plist" \
      "$SCRIPT_DIR/google_services/GoogleService-Info.plist" \
      "$PLIST_DST"; do
    [[ -f "$candidate" ]] && { PLIST_SRC="$candidate"; break; }
  done

  if [[ -z "$PLIST_SRC" ]]; then
    err "GoogleService-Info.plist not found. Looked in:
         • $SCRIPT_DIR/GoogleService-Info.plist
         • $SCRIPT_DIR/google_services/GoogleService-Info.plist
         • $PLIST_DST
       Download it from Firebase Console → Project Settings → Your iOS app."
  fi

  if [[ "$PLIST_SRC" != "$PLIST_DST" ]]; then
    cp "$PLIST_SRC" "$PLIST_DST"
    ok "Copied GoogleService-Info.plist  ($PLIST_SRC → ios/Runner/)"
  else
    ok "GoogleService-Info.plist already in place at ios/Runner/"
  fi

  # ── Read BUNDLE_ID from GoogleService-Info.plist ──────────────
  local bundle_id
  bundle_id=$(grep -A1 "<key>BUNDLE_ID</key>" "$PLIST_DST" \
    | grep "<string>" \
    | sed 's|.*<string>||;s|</string>.*||' \
    | xargs 2>/dev/null || true)

  if [[ -n "$bundle_id" ]]; then
    if [[ "$bundle_id" == "$IOS_BUNDLE_ID" ]]; then
      ok "GoogleService-Info.plist BUNDLE_ID ✔ → $bundle_id"
    else
      warn "GoogleService-Info.plist BUNDLE_ID mismatch!"
      warn "  Expected : $IOS_BUNDLE_ID"
      warn "  Found    : $bundle_id"
      warn "  Download the correct file from Firebase Console → Your iOS app."
    fi
  else
    warn "Could not read BUNDLE_ID from GoogleService-Info.plist"
  fi

  # ── Sync bundle ID into Xcode project + Info.plist ─────────────
  # The GoogleService-Info.plist BUNDLE_ID is the authoritative source.
  # If the Xcode project or Info.plist still carry a different ID the
  # app will be rejected at signing / App Store validation.
  local sync_id="${bundle_id:-$IOS_BUNDLE_ID}"
  # FIX: pass PLIST_DST explicitly — _patch_ios_bundle_id cannot see
  # copy_ios_files local variables ($PLIST_DST was always empty before).
  _patch_ios_bundle_id "$sync_id" "$PLIST_DST"

  # FIX: register GoogleService-Info.plist in Xcode project so it is
  # bundled at runtime.  Copying the file to ios/Runner/ is necessary
  # but NOT sufficient — without a project.pbxproj entry Firebase cannot
  # find the plist at runtime, causing [core/no-app] crash on iOS.
  _register_plist_in_xcode "$PLIST_DST"
}

# ── Write bundle ID into every iOS location that needs it ────────
# 1. ios/Runner.xcodeproj/project.pbxproj  — PRODUCT_BUNDLE_IDENTIFIER
# 2. ios/Runner/Info.plist                 — CFBundleIdentifier (if hardcoded)
# Uses PlistBuddy for Info.plist and sed for the .pbxproj text format.
# $2 = path to GoogleService-Info.plist (passed explicitly — avoids the
#      $PLIST_DST out-of-scope bug when called from _patch_ios_bundle_id)
_patch_ios_bundle_id() {
  local target_id="$1"
  # FIX: was referencing $PLIST_DST which is a local var in copy_ios_files
  # and is therefore OUT OF SCOPE here — always resolved to empty string,
  # causing REVERSED_CLIENT_ID injection to silently fail.
  local PLIST_DST="${2:-$PROJECT_DIR/ios/Runner/GoogleService-Info.plist}"
  local PBXPROJ="$PROJECT_DIR/ios/Runner.xcodeproj/project.pbxproj"
  local INFO_PLIST="$PROJECT_DIR/ios/Runner/Info.plist"

  # ── 1. project.pbxproj ───────────────────────────────────────
  if [[ ! -f "$PBXPROJ" ]]; then
    warn "project.pbxproj not found — skipping bundle ID sync in Xcode project"
  else
    local current_pbx
    current_pbx=$(grep "PRODUCT_BUNDLE_IDENTIFIER" "$PBXPROJ" \
      | head -1 | sed 's/.*= *//;s/[;[:space:]]*//' || true)

    if [[ "$current_pbx" == "$target_id" ]]; then
      ok "project.pbxproj PRODUCT_BUNDLE_IDENTIFIER ✔ → $target_id"
    else
      _sed_i "s|PRODUCT_BUNDLE_IDENTIFIER = [^;]*;|PRODUCT_BUNDLE_IDENTIFIER = ${target_id};|g" "$PBXPROJ"
      ok "project.pbxproj PRODUCT_BUNDLE_IDENTIFIER → $target_id  (was: ${current_pbx:-?})"
    fi
  fi

  # ── 2. Info.plist — CFBundleIdentifier ───────────────────────
  # Flutter-generated Info.plist uses the $(PRODUCT_BUNDLE_IDENTIFIER)
  # variable, so it only needs patching when hardcoded to a literal value.
  if [[ ! -f "$INFO_PLIST" ]]; then
    warn "Info.plist not found — skipping CFBundleIdentifier patch"
    return
  fi

  local current_info=""
  if command -v /usr/libexec/PlistBuddy &>/dev/null; then
    current_info=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$INFO_PLIST" 2>/dev/null || true)
    # Only patch if the value is a literal (not a $(VAR) reference)
    if [[ "$current_info" == *'$('* ]]; then
      ok "Info.plist CFBundleIdentifier uses Xcode variable — no patch needed"
    elif [[ "$current_info" == "$target_id" ]]; then
      ok "Info.plist CFBundleIdentifier ✔ → $target_id"
    elif [[ -n "$current_info" ]]; then
      /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $target_id" "$INFO_PLIST" 2>/dev/null \
        && ok "Info.plist CFBundleIdentifier → $target_id  (was: $current_info)" \
        || warn "Could not update CFBundleIdentifier in Info.plist — check manually"
    fi
  else
    # Fallback: sed — skip variable-style values
    if grep -q "CFBundleIdentifier" "$INFO_PLIST" && \
       ! grep -A1 "CFBundleIdentifier" "$INFO_PLIST" | grep -q '\$('; then
      _sed_i "/<key>CFBundleIdentifier<\/key>/{n;s|<string>[^<]*<\/string>|<string>${target_id}<\/string>|;}" "$INFO_PLIST" 2>/dev/null \
        && ok "Info.plist CFBundleIdentifier → $target_id (via sed)" \
        || warn "sed patch of CFBundleIdentifier failed — check manually"
    else
      ok "Info.plist CFBundleIdentifier uses Xcode variable — no patch needed"
    fi
  fi

  # ── Inject REVERSED_CLIENT_ID into ios/Runner/Info.plist ────
  # Google Sign-In requires the REVERSED_CLIENT_ID as a URL scheme.
  local reversed_id
  reversed_id=$(grep -A1 "<key>REVERSED_CLIENT_ID</key>" "$PLIST_DST" \
    | grep "<string>" \
    | sed 's|.*<string>||;s|</string>.*||' \
    | xargs 2>/dev/null || true)

  local INFO_PLIST="$PROJECT_DIR/ios/Runner/Info.plist"
  if [[ -z "$reversed_id" ]]; then
    warn "REVERSED_CLIENT_ID not found in GoogleService-Info.plist — Google Sign-In may fail"
  elif [[ ! -f "$INFO_PLIST" ]]; then
    warn "ios/Runner/Info.plist not found — skipping URL scheme injection"
  else
    # FIX: always call _inject_url_scheme — it strips stale
    # com.googleusercontent.apps.* entries before writing, so re-runs
    # with a changed client ID (or leftovers from a previous run) can
    # never leave the wrong scheme silently in place.
    # The old guard skipped injection whenever ANY reversed client ID was
    # present, even if it was a stale value from a different OAuth client.
    info "Ensuring REVERSED_CLIENT_ID URL scheme in ios/Runner/Info.plist → $reversed_id"
    _inject_url_scheme "$reversed_id" "$INFO_PLIST"
  fi
}

# ── Register GoogleService-Info.plist in Xcode project ───────────
# ROOT CAUSE of [core/no-app] on iOS:
#   Copying GoogleService-Info.plist to ios/Runner/ puts the file on disk,
#   but Xcode only bundles files listed in project.pbxproj under:
#     1. PBXFileReference section  (declares the file exists)
#     2. PBXBuildFile section      (declares it should be built/copied)
#     3. PBXResourcesBuildPhase    ("Copy Bundle Resources" phase)
#   Without all three, Firebase.initializeApp() crashes with [core/no-app]
#   because the plist is absent from the compiled .app bundle.
#
# FIX:
#   Use ruby/xcodeproj gem if available (safest).
#   Fall back to direct sed injection into project.pbxproj.
_register_plist_in_xcode() {
  local PLIST_FILE="$1"
  local PBXPROJ="$PROJECT_DIR/ios/Runner.xcodeproj/project.pbxproj"

  hdr "Step 3: iOS — register GoogleService-Info.plist in Xcode"

  if [[ ! -f "$PBXPROJ" ]]; then
    warn "project.pbxproj not found — cannot register plist in Xcode"
    return
  fi

  # Already registered?
  if grep -q "GoogleService-Info.plist" "$PBXPROJ"; then
    ok "GoogleService-Info.plist already referenced in project.pbxproj"
    return
  fi

  # Strategy 1: xcodeproj Ruby gem (cleanest, handles all edge-cases)
  if command -v ruby &>/dev/null && ruby -e "require 'xcodeproj'" 2>/dev/null; then
    info "Using xcodeproj gem to add GoogleService-Info.plist to Xcode target"
    ruby - "$PROJECT_DIR" "$PLIST_FILE" << 'RUBYEOF'
require 'xcodeproj'
project_path = File.join(ARGV[0], 'ios', 'Runner.xcodeproj')
plist_path   = ARGV[1]
proj   = Xcodeproj::Project.open(project_path)
target = proj.targets.find { |t| t.name == 'Runner' }
unless target; warn "Runner target not found"; exit 1; end
group = proj.main_group.find_subpath('Runner', true)
ref   = group.files.find { |f| f.path == 'GoogleService-Info.plist' }
ref ||= group.new_file(plist_path)
phase = target.resources_build_phase
phase.add_file_reference(ref) unless phase.files_references.include?(ref)
proj.save
puts "  ✔  GoogleService-Info.plist added to Runner target via xcodeproj gem"
RUBYEOF
    if grep -q "GoogleService-Info.plist" "$PBXPROJ"; then
      ok "GoogleService-Info.plist registered (xcodeproj gem)"
      return
    fi
  fi

  # Strategy 2: python3 mod_pbxproj
  if python3 -c "import mod_pbxproj" 2>/dev/null; then
    info "Using mod_pbxproj to add GoogleService-Info.plist"
    python3 - "$PROJECT_DIR" << 'PYEOF2'
import sys
from mod_pbxproj import XcodeProject
proj = XcodeProject.Load(sys.argv[1] + '/ios/Runner.xcodeproj/project.pbxproj')
proj.add_file('Runner/GoogleService-Info.plist', target_name='Runner', tree='SOURCE_ROOT')
proj.save()
print("  ✔  GoogleService-Info.plist added via mod_pbxproj")
PYEOF2
    if grep -q "GoogleService-Info.plist" "$PBXPROJ"; then
      ok "GoogleService-Info.plist registered (mod_pbxproj)"
      return
    fi
  fi

  # Strategy 3: Direct sed injection into project.pbxproj
  # Deterministic UUIDs based on bundle ID so re-runs are idempotent.
  info "Injecting GoogleService-Info.plist into project.pbxproj via sed (last resort)"
  local FILE_REF_UUID BUILDFILE_UUID
  if command -v md5sum &>/dev/null; then
    FILE_REF_UUID=$(echo "${IOS_BUNDLE_ID}_plist_fileref"  | md5sum | tr '[:lower:]' '[:upper:]' | cut -c1-24)
    BUILDFILE_UUID=$(echo "${IOS_BUNDLE_ID}_plist_buildfile" | md5sum | tr '[:lower:]' '[:upper:]' | cut -c1-24)
  else
    FILE_REF_UUID=$(echo "${IOS_BUNDLE_ID}_plist_fileref"  | md5 | tr '[:lower:]' '[:upper:]' | cut -c1-24)
    BUILDFILE_UUID=$(echo "${IOS_BUNDLE_ID}_plist_buildfile" | md5 | tr '[:lower:]' '[:upper:]' | cut -c1-24)
  fi
  FILE_REF_UUID="${FILE_REF_UUID:0:24}"
  BUILDFILE_UUID="${BUILDFILE_UUID:0:24}"

  if ! grep -q "Begin PBXFileReference section" "$PBXPROJ"; then
    warn "Cannot locate PBXFileReference section in project.pbxproj"
    warn "Fix manually: open Xcode → right-click Runner group → Add Files → GoogleService-Info.plist → check 'Add to targets: Runner'"
    return
  fi

  # 1. PBXFileReference
  _sed_i "s|/\\* Begin PBXFileReference section \\*/|/* Begin PBXFileReference section */\n\t\t${FILE_REF_UUID} /* GoogleService-Info.plist */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.plist.xml; path = \"GoogleService-Info.plist\"; sourceTree = \"<group>\"; };|" "$PBXPROJ" 2>/dev/null || true

  # 2. PBXBuildFile
  _sed_i "s|/\\* Begin PBXBuildFile section \\*/|/* Begin PBXBuildFile section */\n\t\t${BUILDFILE_UUID} /* GoogleService-Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = ${FILE_REF_UUID} /* GoogleService-Info.plist */; };|" "$PBXPROJ" 2>/dev/null || true

  if grep -q "GoogleService-Info.plist" "$PBXPROJ"; then
    ok "GoogleService-Info.plist injected into project.pbxproj via sed"
    warn "Open Xcode once to verify Resources build phase includes GoogleService-Info.plist."
    warn "If missing: Xcode → Runner target → Build Phases → Copy Bundle Resources → '+'"
  else
    warn "Automatic injection failed. Fix manually:"
    warn "  1. Open ios/Runner.xcworkspace in Xcode"
    warn "  2. Right-click Runner group → Add Files to 'Runner'"
    warn "  3. Select ios/Runner/GoogleService-Info.plist"
    warn "  4. Ensure 'Add to targets: Runner' is checked → Add"
  fi
}


# ── Inject a URL scheme into Info.plist (robust, 3-strategy) ──
# Strategy 1: PlistBuddy  (macOS native — most reliable, handles binary + XML)
# Strategy 2: python3 plistlib  (cross-platform, handles any plist format)
# Strategy 3: sed fallback  (last resort, XML-only)
#
# FIX: stale REVERSED_CLIENT_ID idempotency bug.
#   The old guard `grep -q "$reversed_id" "$INFO_PLIST"` skipped injection
#   when ANY com.googleusercontent.apps.* scheme was already present — even
#   the wrong one from a previous run with a different client ID.
#   The fix is to ALWAYS strip every com.googleusercontent.apps.* entry
#   before writing, so the correct value is always the only one present.
_strip_stale_reversed_client_id() {
  local INFO_PLIST="$1"

  # ── Strip via python3 plistlib (handles binary + XML) ──────
  if command -v python3 &>/dev/null; then
    python3 - "$INFO_PLIST" <<'PYEOF' 2>/dev/null || true
import sys, plistlib, pathlib

plist_path = pathlib.Path(sys.argv[1])
with open(plist_path, 'rb') as fh:
    data = plistlib.load(fh)

url_types = data.get('CFBundleURLTypes', [])
cleaned = []
removed = 0
for entry in url_types:
    schemes = entry.get('CFBundleURLSchemes', [])
    # Drop any entry whose scheme is a reversed Google OAuth client ID
    if any(s.startswith('com.googleusercontent.apps.') for s in schemes):
        removed += 1
    else:
        cleaned.append(entry)

if removed:
    data['CFBundleURLTypes'] = cleaned
    with open(plist_path, 'wb') as fh:
        plistlib.dump(data, fh, fmt=plistlib.FMT_XML)
    print(f"  stripped {removed} stale REVERSED_CLIENT_ID scheme(s) from Info.plist")
PYEOF
    return
  fi

  # ── Fallback: sed strip (XML only) ─────────────────────────
  # Remove <dict>…</dict> blocks containing com.googleusercontent.apps.*
  # This is best-effort; python3 path above is strongly preferred.
  _sed_i '/com\.googleusercontent\.apps\./,/<\/dict>/{
    /<\/dict>/d
    d
  }' "$INFO_PLIST" 2>/dev/null || true
}

_inject_url_scheme() {
  local reversed_id="$1"
  local INFO_PLIST="$2"

  # ── Always strip stale Google OAuth URL schemes first ──────
  # This makes injection idempotent regardless of what a previous
  # run (or a manual edit) may have written.
  _strip_stale_reversed_client_id "$INFO_PLIST"

  # ── Strategy 1: PlistBuddy ─────────────────────────────────
  if command -v /usr/libexec/PlistBuddy &>/dev/null; then
    info "Using PlistBuddy to inject URL scheme"
    local PLISTBUDDY=/usr/libexec/PlistBuddy

    # Ensure CFBundleURLTypes array exists
    if ! "$PLISTBUDDY" -c "Print :CFBundleURLTypes" "$INFO_PLIST" &>/dev/null; then
      "$PLISTBUDDY" -c "Add :CFBundleURLTypes array" "$INFO_PLIST"
    fi

    # Count existing entries so we append at the end
    local count
    count=$("$PLISTBUDDY" -c "Print :CFBundleURLTypes" "$INFO_PLIST" 2>/dev/null \
      | grep -c "^    Dict" || true)
    count="${count:-0}"

    "$PLISTBUDDY" \
      -c "Add :CFBundleURLTypes:${count} dict" \
      -c "Add :CFBundleURLTypes:${count}:CFBundleTypeRole string Editor" \
      -c "Add :CFBundleURLTypes:${count}:CFBundleURLSchemes array" \
      -c "Add :CFBundleURLTypes:${count}:CFBundleURLSchemes:0 string ${reversed_id}" \
      "$INFO_PLIST" 2>/dev/null

    if grep -q "$reversed_id" "$INFO_PLIST" 2>/dev/null; then
      ok "REVERSED_CLIENT_ID injected via PlistBuddy → $reversed_id"
      return 0
    fi
    warn "PlistBuddy injection did not verify — trying python3 fallback"
  fi

  # ── Strategy 2: python3 plistlib ───────────────────────────
  if command -v python3 &>/dev/null; then
    info "Using python3 plistlib to inject URL scheme"
    python3 - "$INFO_PLIST" "$reversed_id" <<'PYEOF'
import sys, plistlib, pathlib

plist_path = pathlib.Path(sys.argv[1])
reversed_id = sys.argv[2]

# Load — handles both XML and binary plist
with open(plist_path, 'rb') as fh:
    data = plistlib.load(fh)

url_types = data.setdefault('CFBundleURLTypes', [])

# Stale entries were already stripped by _strip_stale_reversed_client_id;
# this guard is a final safety net in case we are called standalone.
for entry in url_types:
    schemes = entry.get('CFBundleURLSchemes', [])
    if reversed_id in schemes:
        sys.exit(0)

url_types.append({
    'CFBundleTypeRole': 'Editor',
    'CFBundleURLSchemes': [reversed_id],
})

# Always write back as XML so it stays human-readable and git-friendly
with open(plist_path, 'wb') as fh:
    plistlib.dump(data, fh, fmt=plistlib.FMT_XML)
PYEOF

    if grep -q "$reversed_id" "$INFO_PLIST" 2>/dev/null; then
      ok "REVERSED_CLIENT_ID injected via python3 plistlib → $reversed_id"
      return 0
    fi
    warn "python3 injection did not verify — trying sed fallback"
  fi

  # ── Strategy 3: sed (XML plist only, last resort) ──────────
  info "Using sed to inject URL scheme (XML plist assumed)"
  local url_block
  url_block="$(printf '\t<dict>\n\t\t<key>CFBundleTypeRole</key><string>Editor</string>\n\t\t<key>CFBundleURLSchemes</key>\n\t\t<array><string>%s</string></array>\n\t</dict>' "$reversed_id")"

  if grep -q "CFBundleURLTypes" "$INFO_PLIST"; then
    _sed_i "/<key>CFBundleURLTypes<\/key>/{n;s|<array>|<array>\n${url_block}|;}" "$INFO_PLIST" 2>/dev/null
  else
    _sed_i "s|</dict>$|\t<key>CFBundleURLTypes</key>\n\t<array>\n${url_block}\n\t</array>\n</dict>|" "$INFO_PLIST" 2>/dev/null
  fi

  if grep -q "$reversed_id" "$INFO_PLIST" 2>/dev/null; then
    ok "REVERSED_CLIENT_ID injected via sed → $reversed_id"
    return 0
  fi

  # ── All strategies failed — print manual instructions ──────
  warn "All injection strategies failed — add REVERSED_CLIENT_ID manually to ios/Runner/Info.plist"
  warn "  Add this entry inside the <CFBundleURLTypes> array:"
  warn "    <dict>"
  warn "      <key>CFBundleTypeRole</key><string>Editor</string>"
  warn "      <key>CFBundleURLSchemes</key>"
  warn "      <array><string>$reversed_id</string></array>"
  warn "    </dict>"
  return 1
}

# ── Step 3g — Patch ios/Podfile ──────────────────────────────
# Ensures three things that CocoaPods requires:
#   1. source 'https://github.com/CocoaPods/Specs.git' is declared
#      (avoids CDN/HTTP2 failures from cdn.jsdelivr.net trunk).
#   2. platform :ios, '13.0' is declared (suppresses auto-assignment warning).
#   3. use_frameworks! :linkage => :static so Firebase pods link correctly.
patch_ios_podfile() {
  hdr "Step 3: iOS — patch Podfile"

  local PODFILE="$PROJECT_DIR/ios/Podfile"
  if [[ ! -f "$PODFILE" ]]; then
    warn "ios/Podfile not found — skipping Podfile patch (will be created by Flutter)"
    return
  fi

  # ── 1. Switch from CDN to git-based spec repo ──────────────
  # CocoaPods CDN (cdn.jsdelivr.net) is prone to HTTP/2 framing errors.
  # The official git repo is more reliable and is the original source.
  local GIT_SOURCE="source 'https://github.com/CocoaPods/Specs.git'"
  if grep -q "github.com/CocoaPods/Specs" "$PODFILE"; then
    ok "Podfile already uses git-based CocoaPods spec repo"
  else
    # Remove any existing CDN source lines, then prepend the git source
    _sed_i "/^[[:space:]]*source '.*cocoapods.org.*'/d" "$PODFILE" 2>/dev/null || true
    _sed_i "/^[[:space:]]*source '.*cdn\.cocoapods/d"  "$PODFILE" 2>/dev/null || true
    _sed_i "1s|^|${GIT_SOURCE}\n|" "$PODFILE"
    ok "Switched Podfile spec source → git (github.com/CocoaPods/Specs)"
  fi

  # ── 2. Ensure 'platform :ios' is declared ──────────────────
  local IOS_MIN_VERSION="13.0"
  if grep -qE "^[[:space:]]*platform :ios" "$PODFILE"; then
    local current_ver
    current_ver=$(grep -E "^[[:space:]]*platform :ios" "$PODFILE" \
      | head -1 | grep -oE "[0-9]+\.[0-9]+" | head -1 || true)
    if [[ "$current_ver" == "$IOS_MIN_VERSION" ]]; then
      ok "Podfile already has platform :ios, '$IOS_MIN_VERSION'"
    else
      warn "Updating platform :ios from '$current_ver' → '$IOS_MIN_VERSION'"
      _sed_i "s|^[[:space:]]*platform :ios.*|platform :ios, '$IOS_MIN_VERSION'|" "$PODFILE"
      ok "Podfile platform :ios updated → $IOS_MIN_VERSION"
    fi
  else
    _sed_i "1s|^|platform :ios, '$IOS_MIN_VERSION'\n|" "$PODFILE"
    ok "Added platform :ios, '$IOS_MIN_VERSION' to Podfile"
  fi

  # ── 3. Suppress Swift Package Manager warning ───────────────
  if ! grep -q "use_frameworks!" "$PODFILE"; then
    _sed_i "/^platform :ios/a\\
use_frameworks! :linkage => :static" "$PODFILE" 2>/dev/null \
      && ok "Added use_frameworks! :linkage => :static to Podfile" \
      || warn "Could not add use_frameworks! — add it manually after the platform line"
  else
    ok "Podfile already contains use_frameworks!"
  fi

  # ── 4. Ensure post_install raises all pod deployment targets ───
  # Many pods (abseil, BoringSSL-GRPC, AppAuth, etc.) ship with
  # IPHONEOS_DEPLOYMENT_TARGET = 9.0 or 10.0.  Since Xcode 15+ the valid
  # simulator range starts at 12.0, so those values produce build warnings
  # that become errors in future Xcode releases.
  # The post_install hook iterates every pod target and raises the value
  # to IOS_MIN_VERSION (13.0) when it is lower.
  _patch_podfile_post_install "$PODFILE" "$IOS_MIN_VERSION"
}

# ── Inject / update post_install deployment-target hook ──────────
#
# FIX: The previous sed /a\ multi-line injection silently fails on
# macOS BSD sed.  When it failed the marker was never written, so the
# fallback cat>> appended a *second* post_install block — CocoaPods
# rejects that with "Specifying multiple post_install hooks is unsupported."
#
# New approach: use python3 (always present on macOS) to read the
# Podfile as plain text, locate the first post_install block and inject
# our loop right after its opening line, or append a fresh block when
# none exists.  Fully idempotent via MARKER.
#
_patch_podfile_post_install() {
  local PODFILE="$1"
  local MIN_VER="$2"
  local MARKER="# moneyflow-build-tool: deployment target fix"

  # If marker already present, validate the block is syntactically correct.
  # set -e would kill the script if python3 exits non-zero, so we use || true.
  if grep -q "$MARKER" "$PODFILE" 2>/dev/null; then
    local block_ok
    python3 - "$PODFILE" <<'PYEOF' && block_ok=0 || block_ok=1
import sys, re
path = sys.argv[1]
lines = open(path).readlines()
in_block = depth = 0
for line in lines:
    s = line.strip()
    if not in_block and re.match(r'post_install\s+do\b', s):
        in_block = 1
        depth = 1
        continue
    if in_block:
        if not s.startswith('#'):
            depth += s.count('do')
            depth -= s.count('end')
        if depth <= 0:
            sys.exit(0)
sys.exit(1)
PYEOF
    if [[ "${block_ok:-1}" -eq 0 ]]; then
      ok "Podfile post_install deployment-target hook already present"
      return
    fi
    warn "Podfile post_install block is malformed — stripping and rewriting ..."
    python3 - "$PODFILE" <<'PYEOF' || true
import sys, re
path = sys.argv[1]
lines = open(path).readlines()
out = []
in_block = depth = 0
for line in lines:
    s = line.strip()
    if not in_block and re.match(r'post_install\s+do\b', s):
        in_block = 1
        depth = 1
        continue
    if in_block:
        if not s.startswith('#'):
            depth += s.count('do')
            depth -= s.count('end')
        if depth <= 0:
            in_block = 0
            depth = 0
        continue
    out.append(line)
open(path, 'w').write("".join(out).rstrip() + "\n")
PYEOF
  fi

  if ! command -v python3 &>/dev/null; then
    warn "python3 not found — cannot patch post_install block automatically"
    warn "Add the deployment-target loop manually inside your post_install block."
    return
  fi

  info "Injecting deployment-target fix into Podfile post_install block ..."

  python3 - "$PODFILE" "$MIN_VER" "$MARKER" <<'PYEOF' || true
import sys, re
podfile_path = sys.argv[1]
min_ver      = sys.argv[2]
marker       = sys.argv[3]

inject_lines = (
    "  " + marker + "\n"
    "  installer.pods_project.targets.each do |target|\n"
    "    flutter_additional_ios_build_settings(target)\n"
    "    target.build_configurations.each do |config|\n"
    "      min = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']\n"
    "      if min.to_f < " + min_ver + ".to_f\n"
    "        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '" + min_ver + "'\n"
    "      end\n"
    "    end\n"
    "  end\n"
)

content = open(podfile_path).read()
if marker in content:
    sys.exit(0)

pattern = re.compile(r'(^post_install\s+do\s+\|[^|]*\|[^\n]*\n)', re.MULTILINE)
m = pattern.search(content)
if m:
    insert_at = m.end()
    new_content = content[:insert_at] + inject_lines + content[insert_at:]
    open(podfile_path, 'w').write(new_content)
    sys.exit(0)

new_block = "\npost_install do |installer|\n" + inject_lines + "end\n"
open(podfile_path, 'a').write(new_block)
PYEOF

  local rc=$?
  if [[ $rc -eq 0 ]] && grep -q "$MARKER" "$PODFILE" 2>/dev/null; then
    ok "Podfile post_install deployment-target hook injected (min iOS $MIN_VER)"
  else
    warn "Could not auto-patch Podfile post_install block."
    warn "Add the deployment-target loop manually inside your post_install block."
  fi
}

#
fix_podfile_duplicate_post_install() {
  local PODFILE="$PROJECT_DIR/ios/Podfile"
  if [[ ! -f "$PODFILE" ]]; then return; fi

  local count
  count=$(grep -c "^post_install" "$PODFILE" 2>/dev/null || true)
  if [[ "$count" -le 1 ]]; then
    return  # only one (or zero) block — nothing to fix
  fi

  warn "Podfile has $count post_install blocks — stripping all and rewriting one clean block ..."

  # Strategy: remove ALL post_install blocks entirely, then let
  # _patch_podfile_post_install write a single correct block fresh.
  # This is safer than trying to merge blocks whose end keywords may
  # have been lost or duplicated by earlier bad patches.
  python3 - "$PODFILE" <<'PYEOF'
import sys, re

path = sys.argv[1]
with open(path, 'r') as fh:
    lines = fh.readlines()

out = []
in_block = False
depth = 0

for line in lines:
    s = line.strip()
    if not in_block and re.match(r'post_install\s+do', s):
        in_block = True
        depth = 1
        continue
    if in_block:
        # Only count do/end on lines that are not comments
        if not s.startswith('#'):
            depth += len(re.findall(r'do', s))
            depth -= s.count('end')
        if depth <= 0:
            in_block = False
            depth = 0
        continue
    out.append(line)

result = "".join(out).rstrip() + "\n"
with open(path, 'w') as fh:
    fh.write(result)

remaining = sum(1 for l in result.splitlines() if re.match(r'post_install\s+do', l.strip()))
print(f"Removed all post_install blocks. Remaining: {remaining}")
PYEOF

  local rc=$?
  local remaining
  remaining=$(grep -c "^post_install" "$PODFILE" 2>/dev/null || echo "?")
  if [[ $rc -eq 0 && "$remaining" == "0" ]]; then
    ok "All post_install blocks removed — will write one clean block now"
    # Clear the marker so _patch_podfile_post_install writes a fresh block
    local MARKER="# moneyflow-build-tool: deployment target fix"
    # (marker is already gone since we stripped the blocks — this is a no-op)
  else
    warn "Could not fully strip post_install blocks ($remaining remain)."
    warn "Manually remove all post_install blocks from ios/Podfile and re-run."
  fi
}

# ── Step 4 — pod install ─────────────────────────────────────
# Runs pod install with a 3-attempt strategy to handle CDN flakiness:
#   Attempt 1: pod install --no-repo-update  (fast — uses local cache)
#   Attempt 2: pod install --repo-update     (refreshes git spec repo)
#   Attempt 3: Detects CDN errors, forces Podfile to git source, retries
pod_install() {
  hdr "Step 4: pod install"
  if ! command -v pod &>/dev/null; then
    err "CocoaPods not found. Install with: sudo gem install cocoapods"
  fi

  cd "$PROJECT_DIR/ios"

  local PODFILE="$PROJECT_DIR/ios/Podfile"

  # ── Attempt 1: fast path — no repo update (uses cached specs) ──
  info "pod install --no-repo-update  (attempt 1/3 — fast path)"
  local pod_out pod_rc
  pod_out=$(pod install --no-repo-update 2>&1) && pod_rc=0 || pod_rc=$?

  if [[ $pod_rc -eq 0 ]]; then
    cd "$PROJECT_DIR"
    ok "pod install complete (fast path)"
    return 0
  fi

  # ── Attempt 2: full repo update ────────────────────────────────
  info "Fast path failed — retrying with --repo-update  (attempt 2/3)"
  pod_out=$(pod install --repo-update 2>&1) && pod_rc=0 || pod_rc=$?

  if [[ $pod_rc -eq 0 ]]; then
    cd "$PROJECT_DIR"
    ok "pod install complete (with repo update)"
    return 0
  fi

  # ── Attempt 3: CDN error detected — switch to git spec source ──
  # "Error in the HTTP2 framing layer" and "CDN: trunk URL couldn't be
  # downloaded" both indicate the jsdelivr.net CDN is unreachable.
  # Switching the source line to github.com/CocoaPods/Specs bypasses it.
  if echo "$pod_out" | grep -qE "CDN|HTTP2|jsdelivr|trunk URL"; then
    warn "CocoaPods CDN unreachable (HTTP/2 error) — switching to git spec repo"

    local GIT_SOURCE="source 'https://github.com/CocoaPods/Specs.git'"
    if ! grep -q "github.com/CocoaPods/Specs" "$PODFILE"; then
      _sed_i "/^[[:space:]]*source '.*cocoapods.org.*'/d" "$PODFILE" 2>/dev/null || true
      _sed_i "/^[[:space:]]*source '.*cdn/d"              "$PODFILE" 2>/dev/null || true
      _sed_i "1s|^|${GIT_SOURCE}\n|" "$PODFILE"
      ok "Podfile source switched to git repo"
    fi

    info "pod install --repo-update  (attempt 3/3 — git source)"
    pod_out=$(pod install --repo-update 2>&1) && pod_rc=0 || pod_rc=$?

    if [[ $pod_rc -eq 0 ]]; then
      cd "$PROJECT_DIR"
      ok "pod install complete (git source fallback)"
      return 0
    fi
  fi

  # ── All attempts failed — print full output and abort ──────────
  cd "$PROJECT_DIR"
  echo "$pod_out"
  err "pod install failed after 3 attempts. See output above for details."
}

# ── Pick an Android target (emulator or real device) ─────────
# Sets the global ANDROID_DEVICE_ID used by flutter run -d
ANDROID_DEVICE_ID=""

# -- Sub-step: list and pick from available emulators ----------
_pick_emulator() {
  hdr "Step 4b: Select Emulator"
  echo ""
  info "Fetching available emulators..."

  local raw
  raw=$(flutter emulators 2>/dev/null || true)

  local -a emu_ids emu_labels
  local idx=0

  while IFS= read -r line; do
    [[ -z "$line" ]]                          && continue
    [[ "$line" == *"available emulator"* ]]   && continue
    [[ "$line" == *"No emulators"* ]]         && continue
    [[ "$line" == *"flutter emulators"* ]]    && continue
    [[ "$line" != *"•"* ]]                    && continue

    local emu_id emu_name platform
    if [[ "$line" =~ ^[[:space:]]*• ]]; then
      # Old format:  • avd_id • Display Name • platform
      emu_id=$(  echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}')
      emu_name=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$3); print $3}')
      platform=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$4); print $4}')
    else
      # New format:  avd_id • Display Name • Brand • platform
      emu_id=$(  echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$1); print $1}')
      emu_name=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}')
      platform=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$4); print $4}')
    fi

    [[ "$emu_id"   == *"ios"* || "$emu_id"   == *"apple"* ]] && continue
    [[ "$emu_name" == *"iOS"* || "$emu_name" == *"Apple"* ]] && continue
    [[ "$platform" == *"ios"* || "$platform" == *"apple"* ]] && continue
    [[ "$emu_id" == "Id" || "$emu_id" == "Name" ]]           && continue
    [[ -z "$emu_id" ]]                                        && continue

    idx=$((idx+1))
    emu_ids[$idx]="$emu_id"
    emu_labels[$idx]="${emu_name:-$emu_id}  [$emu_id]"
  done <<< "$raw"

  # Strategy 2: avdmanager fallback (Android AVDs only)
  if [[ $idx -eq 0 ]]; then
    local avdmanager
    avdmanager=$(command -v avdmanager 2>/dev/null \
      || find "$HOME/Library/Android/sdk" -name avdmanager 2>/dev/null | head -1 \
      || true)

    if [[ -n "$avdmanager" ]]; then
      local avd_name="" avd_tag=""
      while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*Name:[[:space:]]+(.*) ]]; then
          avd_name="${BASH_REMATCH[1]}"
          avd_tag=""
        fi
        if [[ "$line" =~ Tag/ABI:[[:space:]]+(.*) ]]; then
          avd_tag="${BASH_REMATCH[1]}"
          if [[ -n "$avd_name" ]]; then
            [[ "$avd_tag" == *"ios"* || "$avd_tag" == *"apple"* ]] && { avd_name=""; continue; }
            idx=$((idx+1))
            emu_ids[$idx]="$avd_name"
            emu_labels[$idx]="$avd_name  [$avd_tag]"
            avd_name=""
          fi
        fi
      done < <("$avdmanager" list avd 2>/dev/null)
    fi
  fi

  if [[ $idx -eq 0 ]]; then
    warn "No emulators found by flutter or avdmanager."
    echo ""
    echo "  Raw output from \`flutter emulators\`:"
    echo "$raw" | sed 's/^/    /'
    echo ""
    echo "  Possible fixes:"
    echo "    • Open Android Studio → Device Manager and confirm AVDs exist"
    echo "    • Run: flutter emulators   (manually check output)"
    echo "    • Ensure ANDROID_HOME or ANDROID_SDK_ROOT is set correctly"
    echo ""
    printf "  Press Enter to retry (or Ctrl-C to abort)... "
    read -r
    _pick_emulator; return
  fi

  for i in $(seq 1 $idx); do
    echo "   $i)  🤖  ${emu_labels[$i]}"
  done
  echo ""
  printf "  Select emulator [1-$idx]: "
  local sel; read -r sel
  if ! [[ "$sel" =~ ^[0-9]+$ ]] || [[ $sel -lt 1 ]] || [[ $sel -gt $idx ]]; then
    warn "Invalid — try again."; _pick_emulator; return
  fi

  local chosen="${emu_ids[$sel]}"

  # ── FIX: Check if this AVD is already running before launching ──
  # Launching an already-running emulator causes "already running as process NNNN" error.
  # Detect by matching the chosen AVD name against live flutter devices output.
  local already_running=""
  already_running=$(flutter devices 2>/dev/null     | grep -i "emulator\|android"     | grep -i "${chosen//_/ }"     | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}'     | head -1 || true)

  # Broader fallback: any emulator already online
  if [[ -z "$already_running" ]]; then
    already_running=$(flutter devices 2>/dev/null       | grep -i "emulator-[0-9]"       | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}'       | head -1 || true)
  fi

  if [[ -n "$already_running" ]]; then
    ANDROID_DEVICE_ID="$already_running"
    ok "Emulator already running — reusing device id: $ANDROID_DEVICE_ID"
  else
    info "Launching emulator: $chosen"
    flutter emulators --launch "$chosen" || true   # ignore non-fatal "already running" stderr
    echo ""
    info "Waiting for emulator to boot (up to 120s)..."
    local waited=0
    while true; do
      local booted
      booted=$(flutter devices 2>/dev/null | grep -i "android\|emulator" || true)
      [[ -n "$booted" ]] && break
      sleep 3; waited=$((waited+3))
      printf "."
      [[ $waited -ge 120 ]] && err "Emulator did not boot within 120s. Aborting."
    done
    ANDROID_DEVICE_ID=$(flutter devices 2>/dev/null       | grep -i "android\|emulator"       | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}'       | head -1)
    echo ""; ok "Emulator booted → device id: $ANDROID_DEVICE_ID"
  fi
}

# -- Sub-step: list and pick from connected real devices -------
_pick_real_device() {
  hdr "Step 4b: Select Real Device"
  echo ""
  info "Scanning for connected Android devices..."
  echo "  Make sure USB debugging is enabled on your phone."
  echo "  (Settings → Developer Options → USB Debugging)"
  echo ""

  local raw
  raw=$(flutter devices 2>/dev/null | grep -i "android\|sdk built" || true)

  local -a dev_ids dev_labels
  local idx=0
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    local dev_id dev_name
    dev_id=$(echo "$line"   | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}')
    dev_name=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$1); print $1}')
    [[ -z "$dev_id" ]] && continue
    idx=$((idx+1))
    dev_ids[$idx]="$dev_id"
    dev_labels[$idx]="$dev_name  ($dev_id)"
  done <<< "$raw"

  if [[ $idx -eq 0 ]]; then
    warn "No real Android device detected."
    echo ""
    printf "  Connect your device via USB, then press Enter to retry (or Ctrl-C to abort)... "
    read -r
    _pick_real_device; return
  fi

  for i in $(seq 1 $idx); do
    echo "   $i)  📱  ${dev_labels[$i]}"
  done
  echo ""
  printf "  Select device [1-$idx]: "
  local sel; read -r sel
  if ! [[ "$sel" =~ ^[0-9]+$ ]] || [[ $sel -lt 1 ]] || [[ $sel -gt $idx ]]; then
    warn "Invalid — try again."; _pick_real_device; return
  fi

  ANDROID_DEVICE_ID="${dev_ids[$sel]}"
  ok "Device selected: $ANDROID_DEVICE_ID"
}

# -- Main picker: ask emulator vs real device first ------------
pick_android_device() {
  hdr "Step 4: Select Android target type"
  echo ""
  echo "   1)  🤖  Emulator  (Android Virtual Device)"
  echo "   2)  📱  Real Device  (USB / Wi-Fi ADB)"
  echo ""
  printf "  Choose [1-2]: "
  local choice; read -r choice
  case "$choice" in
    1) _pick_emulator    ;;
    2) _pick_real_device ;;
    *) warn "Invalid — enter 1 or 2."; pick_android_device ;;
  esac
  ok "Target ready → $ANDROID_DEVICE_ID"
}

# ═══════════════════════════════════════════════════════════════
#  ANDROID
# ═══════════════════════════════════════════════════════════════

# ── Uninstall app if signature mismatch would block install ──────
# INSTALL_FAILED_UPDATE_INCOMPATIBLE occurs when the installed APK was signed
# with a different key (e.g. debug key) than the one being installed now.
# Silently uninstalling first is the standard fix.
uninstall_if_incompatible() {
  local device_id="$1"
  if ! command -v adb &>/dev/null; then
    warn "adb not found — skipping signature-conflict check"
    return
  fi

  local installed_sig
  installed_sig=$(adb -s "$device_id" shell pm list packages 2>/dev/null     | grep "$PACKAGE_NAME" || true)

  if [[ -n "$installed_sig" ]]; then
    info "App already installed on $device_id — uninstalling to avoid signature mismatch"
    adb -s "$device_id" uninstall "$PACKAGE_NAME" 2>/dev/null &&       ok "Uninstalled $PACKAGE_NAME (signature conflict prevention)" ||       warn "Uninstall failed — install may fail with INSTALL_FAILED_UPDATE_INCOMPATIBLE"
  fi
}


# ── patch_main_activity ───────────────────────────────────────
# Ensures MainActivity.kt (or .java) lives at the path Android
# expects for the current PACKAGE_NAME, and that its `package`
# declaration matches.  This is the fix for:
#   ClassNotFoundException: <package>.MainActivity
# which happens when the file sits in a stale package directory
# from a previous name, or was never moved after renaming.
patch_main_activity() {
  hdr "Step 3: Android — patch MainActivity package"

  local pkg_path="${PACKAGE_NAME//.//}"   # co.tpcreative... → co/tpcreative/...
  local kotlin_dir="$PROJECT_DIR/android/app/src/main/kotlin"
  local java_dir="$PROJECT_DIR/android/app/src/main/java"
  local target_dir=""
  local ext=""

  # Determine whether project uses kotlin/ or java/ source root
  if [[ -d "$kotlin_dir" ]]; then
    target_dir="$kotlin_dir/$pkg_path"
    ext="kt"
  else
    target_dir="$java_dir/$pkg_path"
    ext="java"
  fi

  local target_file="$target_dir/MainActivity.$ext"

  # ── Find the existing MainActivity (may be in a different package dir) ──
  local found=""
  found=$(find "$PROJECT_DIR/android/app/src/main"     -name "MainActivity.$ext" 2>/dev/null | head -1 || true)

  if [[ -z "$found" ]]; then
    # No MainActivity at all — create a minimal one
    warn "MainActivity.$ext not found — creating a default one"
    mkdir -p "$target_dir"
    if [[ "$ext" == "kt" ]]; then
      cat > "$target_file" <<KOTLIN
package $PACKAGE_NAME

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity()
KOTLIN
    else
      cat > "$target_file" <<JAVA
package $PACKAGE_NAME;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {}
JAVA
    fi
    ok "Created $target_file"
    return
  fi

  # ── Fix package declaration inside the file ──
  local current_pkg=""
  current_pkg=$(grep -E "^package " "$found" | head -1 | awk '{print $2}' | tr -d ';' || true)

  if [[ "$current_pkg" != "$PACKAGE_NAME" ]]; then
    warn "MainActivity.$ext has wrong package: '$current_pkg' → fixing to '$PACKAGE_NAME'"
    _sed_i "s|^package .*|package $PACKAGE_NAME|" "$found"
    ok "Package declaration updated in $found"
  fi

  # ── Move the file to the correct directory if needed ──
  if [[ "$found" != "$target_file" ]]; then
    warn "MainActivity.$ext is at wrong path — moving to correct package directory"
    mkdir -p "$target_dir"
    cp "$found" "$target_file"
    # Remove old file only if it differs from target (avoid self-deletion)
    [[ "$found" != "$target_file" ]] && rm -f "$found"
    # Clean up now-empty parent directories
    local old_dir; old_dir=$(dirname "$found")
    while [[ "$old_dir" != "$kotlin_dir" && "$old_dir" != "$java_dir" ]]; do
      rmdir "$old_dir" 2>/dev/null || break
      old_dir=$(dirname "$old_dir")
    done
    ok "Moved → $target_file"
  else
    ok "MainActivity.$ext is at correct path with correct package ✔"
  fi
}

android_common() {
  check_deps
  flutter_clean_get
  patch_android_gradle      # writes settings.gradle.kts, build.gradle.kts, app/build.gradle.kts
  patch_main_activity       # ensures MainActivity.kt is at correct path with correct package
  setup_key_properties      # reads key/key.txt + key/mobile.jks → android/key.properties
  copy_android_files        # copies google-services.json, validates package + project IDs
}

run_android_debug() {
  echo -e "\n${BOLD}▶  Android — Run Debug${RESET}"
  echo "  ──────────────────────────────────────────────"
  android_common
  pick_android_device
  uninstall_if_incompatible "$ANDROID_DEVICE_ID"
  hdr "Step 5: Run on Android (debug)"
  info "flutter run -d \"$ANDROID_DEVICE_ID\" --debug"
  flutter run -d "$ANDROID_DEVICE_ID" --debug
}

run_android_release() {
  echo -e "\n${BOLD}▶  Android — Run Release${RESET}"
  echo "  ──────────────────────────────────────────────"
  android_common
  pick_android_device
  uninstall_if_incompatible "$ANDROID_DEVICE_ID"
  hdr "Step 5: Run on Android (release)"
  info "flutter run -d \"$ANDROID_DEVICE_ID\" --release"
  flutter run -d "$ANDROID_DEVICE_ID" --release
}

build_android_release() {
  echo -e "\n${BOLD}▶  Android — Build Release APK + AAB${RESET}"
  echo "  ──────────────────────────────────────────────"
  android_common
  hdr "Step 4: Build APK"
  info "flutter build apk --release"
  flutter build apk --release
  hdr "Step 4b: Build AAB"
  info "flutter build appbundle --release"
  flutter build appbundle --release
  ok "Android artifacts ready in build/app/outputs/"
}

# ═══════════════════════════════════════════════════════════════
#  iOS
# ═══════════════════════════════════════════════════════════════

# ── Patch pubspec.yaml Firebase deps for iOS compatibility ────
#
# ROOT CAUSE OF CocoaPods CONFLICT:
#   firebase_core 2.x  →  Firebase iOS SDK 10.x  →  GoogleUtilities ~> 7.12
#   google_sign_in_ios 5.9+ → GoogleSignIn ~> 8.0 → GoogleUtilities = 8.0.0
#   These two ranges (>=7.12 <8.0) and (=8.0.0) are INCOMPATIBLE.
#
# FIX: Upgrade to firebase_core 3.x which targets Firebase iOS SDK 11.x
#   firebase_core 3.x  →  Firebase iOS SDK 11.x  →  GoogleUtilities ~> 8.0
#   Now both chains resolve to GoogleUtilities 8.x  ✔
#
# This function rewrites the firebase_* entries in pubspec.yaml in-place
# ONLY when the installed major version is still 2.x.
# All changes are logged so the developer can review them.
patch_pubspec_firebase_deps() {
  hdr "Step 2b: iOS — patch pubspec.yaml Firebase dependencies"

  local PUBSPEC="$PROJECT_DIR/pubspec.yaml"
  if [[ ! -f "$PUBSPEC" ]]; then
    warn "pubspec.yaml not found at $PROJECT_DIR — skipping"
    return
  fi

  # Detect current firebase_core major version
  local current_ver
  current_ver=$(grep -E "^\s+firebase_core\s*:" "$PUBSPEC" \
    | head -1 \
    | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" \
    | head -1 || true)

  local major="${current_ver%%.*}"

  if [[ -z "$major" ]]; then
    warn "Could not detect firebase_core version in pubspec.yaml — skipping auto-upgrade"
    return
  fi

  if [[ "$major" -ge 3 ]]; then
    ok "firebase_core is already v${current_ver} (3.x+) — no upgrade needed"
    return
  fi

  warn "firebase_core $current_ver uses Firebase iOS SDK 10.x (GoogleUtilities ~> 7.x)"
  warn "google_sign_in_ios 5.9+ needs GoogleUtilities 8.x — INCOMPATIBLE"
  info "Auto-upgrading Firebase Flutter packages to 3.x (Firebase SDK 11.x)..."

  # ── Version map: 2.x → compatible 3.x floor ──────────────────
  # Plain "pkg:version" pairs — no associative arrays (bash 3.2 / macOS safe).
  # Using ^X.Y.Z lets pub pick the newest non-breaking release automatically.
  local UPGRADES="
    firebase_core:^3.6.0
    firebase_auth:^5.3.1
    cloud_firestore:^5.4.4
    firebase_analytics:^11.3.3
    firebase_crashlytics:^4.1.3
    firebase_messaging:^15.1.3
    firebase_storage:^12.3.3
    firebase_remote_config:^5.1.3
    firebase_dynamic_links:^6.0.8
    firebase_in_app_messaging:^0.8.0+3
    firebase_performance:^0.10.0+8
    cloud_functions:^5.1.3
  "

  local patched=0
  local pair pkg new_ver new_ver_num old_line new_line
  while IFS= read -r pair; do
    pair="${pair//[[:space:]]/}"          # strip all whitespace / blank lines
    [[ -z "$pair" ]] && continue
    pkg="${pair%%:*}"                     # everything before first :
    new_ver="${pair#*:}"                  # everything after first :
    new_ver_num="${new_ver#^}"            # strip leading ^ for sed replacement

    # Match lines like:  firebase_core: ^2.32.0  OR  firebase_core: 2.32.0
    if grep -qE "^[[:space:]]+${pkg}[[:space:]]*:" "$PUBSPEC"; then
      old_line=$(grep -E "^[[:space:]]+${pkg}[[:space:]]*:" "$PUBSPEC" | head -1)
      # Replace the semver number, preserving any leading ^
      new_line=$(echo "$old_line" | sed -E "s|(\^?)[0-9]+\.[0-9]+\.[0-9]+([+.][0-9]+)*|\1${new_ver_num}|")
      _sed_i "s|${old_line}|${new_line}|" "$PUBSPEC"
      ok "  $pkg  ->  ${new_ver}  (was: $(echo "$old_line" | xargs))"
      patched=$((patched + 1))
    fi
  done <<< "$UPGRADES"

  if [[ $patched -eq 0 ]]; then
    warn "No Firebase packages found in pubspec.yaml to upgrade"
  else
    ok "$patched Firebase package(s) upgraded in pubspec.yaml"
    info "Run 'flutter pub outdated' after the build to review remaining constraints."
  fi
}

# ── Clear Xcode DerivedData for the Runner project ───────────────
# 'flutter clean' removes Flutter build outputs but leaves Xcode's
# DerivedData intact.  Stale precompiled modules there cause:
#   "Failed to query serialized dependencies"
#   "Module file … could not be read"
# Deleting the Runner-specific DerivedData folder forces a clean rebuild.
clear_derived_data() {
  hdr "Step 2c: iOS — clear stale DerivedData"

  local DERIVED_BASE="$HOME/Library/Developer/Xcode/DerivedData"
  if [[ ! -d "$DERIVED_BASE" ]]; then
    ok "DerivedData folder not found — nothing to clear"
    return
  fi

  # Match Runner-* folders (Flutter iOS projects always use 'Runner' as the scheme)
  local found=0
  for dir in "$DERIVED_BASE"/Runner-*/; do
    [[ -d "$dir" ]] || continue
    info "Removing stale DerivedData: $(basename "$dir")"
    rm -rf "$dir"
    found=$((found + 1))
  done

  if [[ $found -eq 0 ]]; then
    ok "No Runner DerivedData to clear"
  else
    ok "Cleared $found DerivedData folder(s) — Xcode will do a clean build"
  fi
}

# ── iOS device / simulator picker ────────────────────────────
# Sets the global IOS_DEVICE_ID used by flutter run -d.
IOS_DEVICE_ID=""

pick_ios_device() {
  hdr "Step 4b: Select iOS target"
  echo ""

  local -a all_ids all_labels all_types
  local idx=0

  # ── Section 1: Real devices from flutter devices ─────────────
  local real_raw
  real_raw=$(flutter devices 2>/dev/null | grep -iE "ios|iphone|ipad" | grep -iv "simulator" || true)

  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    local dev_name dev_id dev_platform
    dev_name=$(    echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$1); print $1}')
    dev_id=$(      echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}')
    dev_platform=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$3); print $3}')
    [[ -z "$dev_id" ]] && continue
    idx=$((idx + 1))
    all_ids[$idx]="$dev_id"
    all_labels[$idx]="$dev_name  [$dev_id]  ($dev_platform)"
    all_types[$idx]="device"
  done <<< "$real_raw"

  local real_count=$idx

  # ── Section 2: Booted simulators from flutter devices ────────
  local sim_flutter_raw
  sim_flutter_raw=$(flutter devices 2>/dev/null | grep -i "simulator" || true)

  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    local dev_name dev_id dev_platform
    dev_name=$(    echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$1); print $1}')
    dev_id=$(      echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$2); print $2}')
    dev_platform=$(echo "$line" | awk -F'•' '{gsub(/^[[:space:]]+|[[:space:]]+$/,"",$3); print $3}')
    [[ -z "$dev_id" ]] && continue
    idx=$((idx + 1))
    all_ids[$idx]="$dev_id"
    all_labels[$idx]="$dev_name  [$dev_id]  ($dev_platform)"
    all_types[$idx]="booted"
  done <<< "$sim_flutter_raw"

  local booted_count=$((idx - real_count))

  # ── Section 3: Available (not booted) simulators via xcrun ───
  local sim_raw
  sim_raw=$(xcrun simctl list devices available 2>/dev/null     | grep -E "iPhone|iPad" | head -30 || true)

  local -a avail_ids avail_names
  local aidx=0
  while IFS= read -r sline; do
    [[ -z "$sline" ]] && continue
    local sim_name sim_udid
    sim_name=$(echo "$sline" | sed -E 's/ \(.*$//' | xargs)
    sim_udid=$(echo "$sline" | grep -oE '[A-F0-9-]{36}' | head -1 || true)
    [[ -z "$sim_udid" ]] && continue
    # Skip if already booted (already listed above)
    if echo "$sim_flutter_raw" | grep -q "$sim_udid"; then continue; fi
    aidx=$((aidx + 1))
    avail_ids[$aidx]="$sim_udid"
    avail_names[$aidx]="$sim_name"
    idx=$((idx + 1))
    all_ids[$idx]="$sim_udid"
    all_labels[$idx]="$sim_name  [$sim_udid]"
    all_types[$idx]="simulator"
  done <<< "$sim_raw"

  # ── Display unified list ─────────────────────────────────────
  if [[ $idx -eq 0 ]]; then
    err "No iOS devices or simulators found. Connect a device or open Xcode → Simulator."
  fi

  echo ""
  local i
  for i in $(seq 1 $idx); do
    case "${all_types[$i]}" in
      device)    echo "   $i)  📱  ${all_labels[$i]}  ← real device" ;;
      booted)    echo "   $i)  🖥️   ${all_labels[$i]}  ← simulator (running)" ;;
      simulator) echo "   $i)  💤  ${all_labels[$i]}  ← simulator (not running)" ;;
    esac
  done
  echo ""
  printf "  Select target [1-$idx]: "
  local sel; read -r sel
  if ! [[ "$sel" =~ ^[0-9]+$ ]] || [[ $sel -lt 1 ]] || [[ $sel -gt $idx ]]; then
    warn "Invalid — try again."; pick_ios_device; return
  fi

  local chosen_id="${all_ids[$sel]}"
  local chosen_type="${all_types[$sel]}"

  # ── Boot simulator if not already running ────────────────────
  if [[ "$chosen_type" == "simulator" ]]; then
    info "Booting simulator $chosen_id ..."
    xcrun simctl boot "$chosen_id" 2>/dev/null || true
    open -a Simulator 2>/dev/null || true
    info "Waiting for simulator to appear in Flutter (up to 30s)..."
    local waited=0
    while true; do
      local booted
      booted=$(flutter devices 2>/dev/null | grep "$chosen_id" || true)
      [[ -n "$booted" ]] && break
      sleep 3; waited=$((waited + 3))
      printf "."
      [[ $waited -ge 30 ]] && break
    done
    echo ""
    ok "Simulator booted → $chosen_id"
  fi

  IOS_DEVICE_ID="$chosen_id"
  ok "iOS target selected → $IOS_DEVICE_ID  ($chosen_type)"
}

ios_common() {
  check_deps
  patch_pubspec_firebase_deps   # upgrades firebase_core 2.x → 3.x (fixes GoogleUtilities conflict)
  flutter_clean_get             # flutter clean + pub get (picks up upgraded versions)
  clear_derived_data            # removes stale Xcode DerivedData (fixes "Failed to query serialized dependencies")
  copy_ios_files                # copies GoogleService-Info.plist + injects REVERSED_CLIENT_ID
  patch_appdelegate_google_sign_in  # fix SIGABRT: inject GIDConfiguration (GoogleSignIn SDK 7+)
  fix_podfile_duplicate_post_install  # strip any duplicate post_install blocks first
  patch_ios_podfile             # platform :ios, use_frameworks!, post_install deployment-target hook
  pod_install
  patch_xcode_backend           # fixes "xcode_backend.sh: No such file or directory"
}
# ── Patch AppDelegate.swift: inject GIDConfiguration (GoogleSignIn SDK 7+) ──
#
# ROOT CAUSE of SIGABRT at GIDSignIn.m:592:
#   GoogleSignIn SDK 7+ (shipped in google_sign_in_ios 5.9+) removed auto-reading
#   of clientID from GoogleService-Info.plist.  You must now set it explicitly via
#   GIDSignIn.sharedInstance.configuration before any sign-in call.
#   When it is missing, signInWithOptions: throws an NSException → uncaught →
#   SIGABRT crash as seen in the crash report (GIDSignIn.m:592).
#
# FIX:
#   Inject into AppDelegate.swift (before GeneratedPluginRegistrant.register):
#     GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: "…")
#   clientID is read from the GoogleService-Info.plist that was already copied
#   to ios/Runner/ by copy_ios_files, so this step must run AFTER copy_ios_files.
#   The patch is idempotent — re-runs detect the marker and skip.
#
patch_appdelegate_google_sign_in() {
  hdr "Step 4d: iOS — patch AppDelegate for GoogleSignIn SDK 7+ clientID"

  local PLIST_DST="$PROJECT_DIR/ios/Runner/GoogleService-Info.plist"
  local APPDELEGATE="$PROJECT_DIR/ios/Runner/AppDelegate.swift"
  local MARKER="GIDSignIn.sharedInstance.configuration"

  # ── Require AppDelegate.swift ─────────────────────────────────
  if [[ ! -f "$APPDELEGATE" ]]; then
    warn "ios/Runner/AppDelegate.swift not found — skipping GIDConfiguration patch"
    warn "  Add manually before GeneratedPluginRegistrant.register(with: self):"
    warn "    import GoogleSignIn"
    warn "    GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: \"CLIENT_ID\")"
    return
  fi

  # ── Read CLIENT_ID from GoogleService-Info.plist ──────────────
  local client_id=""
  if [[ -f "$PLIST_DST" ]]; then
    client_id=$(grep -A1 "<key>CLIENT_ID</key>" "$PLIST_DST" \
      | grep "<string>" \
      | sed 's|.*<string>||;s|</string>.*||' \
      | xargs 2>/dev/null || true)
  fi

  if [[ -z "$client_id" ]]; then
    warn "Could not read CLIENT_ID from GoogleService-Info.plist — copy_ios_files must run first"
    return
  fi

  # ── Rewrite AppDelegate.swift unconditionally via python3 ─────
  # Strategy: parse the existing file to extract any non-import, non-GIDConfig
  # body content, then emit a canonical file with:
  #   1. Correct import block (deduped, GoogleSignIn included)
  #   2. GIDConfiguration call
  #   3. Original class body (minus any stray imports or duplicate GIDConfig lines)
  # This handles ANY prior corruption: duplicate imports, stray \n literals,
  # mismatched braces from sed fallbacks, etc.
  python3 - "$APPDELEGATE" "$client_id" <<'REWRITE_PY'
import sys, pathlib, re

path      = pathlib.Path(sys.argv[1])
client_id = sys.argv[2]
src       = path.read_text()

MARKER   = "GIDSignIn.sharedInstance.configuration"
REGISTER = "GeneratedPluginRegistrant.register"
config   = f'    GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: "{client_id}")'

# ── Collect all import module names (deduplicated, original order) ──
import_names = list(dict.fromkeys(
    re.findall(r'^import\s+(\S+)', src, re.MULTILINE)
))
if "GoogleSignIn" not in import_names:
    # Insert after Flutter if present, otherwise append
    try:
        idx = import_names.index("Flutter")
        import_names.insert(idx + 1, "GoogleSignIn")
    except ValueError:
        import_names.append("GoogleSignIn")

import_block = "\n".join(f"import {m}" for m in import_names)

# ── Strip ALL import lines from body ─────────────────────────────
body = re.sub(r'^\s*import\s+\S+[ \t]*\n?', '', src, flags=re.MULTILINE)

# ── Strip any existing GIDConfiguration lines ────────────────────
body = re.sub(r'.*GIDSignIn\.sharedInstance\.configuration.*\n?', '', body)

# ── Strip any literal \n or stray artifacts left by previous sed ─
body = body.replace('\\n', '\n')

# ── Trim leading blank lines ──────────────────────────────────────
body = body.lstrip('\n')

# ── Inject config line before GeneratedPluginRegistrant.register ─
if REGISTER in body:
    lines = body.splitlines(keepends=True)
    out = []
    for line in lines:
        if REGISTER in line:
            out.append(config + "\n")
        out.append(line)
    body = "".join(out)
else:
    # Fallback: inject before 'return super.application('
    body = re.sub(
        r'(\s*return super\.application\()',
        config + "\n" + r'\1',
        body,
        count=1
    )

final = import_block + "\n\n" + body
path.write_text(final)
print("  AppDelegate.swift rewritten to canonical form")
print(f"  clientID → {client_id}")
REWRITE_PY

  # ── Verify ───────────────────────────────────────────────────
  if grep -q "$MARKER" "$APPDELEGATE" 2>/dev/null; then
    ok "AppDelegate.swift patched — GIDConfiguration set before plugin registration"
    ok "  clientID → $client_id"
  else
    warn "Auto-patch failed. Add manually to AppDelegate.swift:"
    warn "  import GoogleSignIn   ← at top of file"
    warn "  GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: \"${client_id}\")"
    warn "  ← insert before GeneratedPluginRegistrant.register(with: self)"
  fi
}

# ── Patch Xcode build phase: fix broken xcode_backend.sh path ────
#
# ROOT CAUSE:
#   The "Run Flutter Build Script" build phase in project.pbxproj contains
#   a hardcoded absolute path to xcode_backend.sh that is machine-specific:
#     /packages/flutter_tools/bin/xcode_backend.sh build
#
# FIX:
#   Rewrite it to use $FLUTTER_ROOT so it works on every machine:
#     "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
#
patch_xcode_backend() {
  hdr "Step 4c: iOS — fix xcode_backend.sh path in project.pbxproj"

  local PBXPROJ="$PROJECT_DIR/ios/Runner.xcodeproj/project.pbxproj"
  if [[ ! -f "$PBXPROJ" ]]; then
    warn "project.pbxproj not found — skipping xcode_backend patch"
    return
  fi

  if grep -q 'FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh' "$PBXPROJ"; then
    ok "xcode_backend.sh path already uses \$FLUTTER_ROOT — nothing to fix"
    return
  fi

  if ! grep -q "xcode_backend.sh" "$PBXPROJ"; then
    ok "No xcode_backend.sh reference in project.pbxproj — nothing to fix"
    return
  fi

  info "Patching xcode_backend.sh path in project.pbxproj ..."

  # Replace any path ending in xcode_backend.sh with the $FLUTTER_ROOT form.
  # Handles: /some/absolute/path/xcode_backend.sh
  #          'quoted/path/xcode_backend.sh'
  #          packages/flutter_tools/bin/xcode_backend.sh  (relative)
  _sed_i "s|['\"/]*[^ '\"]*xcode_backend\.sh['\"/]*|\"\$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh\"|g" \
    "$PBXPROJ" 2>/dev/null || true

  if grep -q 'FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh' "$PBXPROJ"; then
    ok "xcode_backend.sh path patched → \"\$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh\""
  else
    warn "Could not auto-patch xcode_backend.sh path."
    warn "Open Xcode → Runner target → Build Phases → Run Flutter Build Script"
    warn "and change the script to:"
    warn "  \"\$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh\" build"
  fi
}


run_ios_debug() {
  echo -e "\n${BOLD}▶  iOS — Run Debug${RESET}"
  echo "  ──────────────────────────────────────────────"
  ios_common
  pick_ios_device
  hdr "Step 5: Run on iOS (debug)"
  info "flutter run -d \"$IOS_DEVICE_ID\" --debug"
  flutter run -d "$IOS_DEVICE_ID" --debug
}

run_ios_release() {
  echo -e "\n${BOLD}▶  iOS — Run Release${RESET}"
  echo "  ──────────────────────────────────────────────"
  ios_common
  pick_ios_device
  hdr "Step 5: Run on iOS (release)"
  info "flutter run -d \"$IOS_DEVICE_ID\" --release"
  flutter run -d "$IOS_DEVICE_ID" --release
}

build_ios_ipa() {
  echo -e "\n${BOLD}▶  iOS — Build Release IPA${RESET}"
  echo "  ──────────────────────────────────────────────"
  ios_common

  hdr "Step 5: xcodebuild archive"
  local ARCHIVE_PATH="$PROJECT_DIR/build/ios/MoneyFlow.xcarchive"
  local EXPORT_PATH="$PROJECT_DIR/build/ios/ipa"
  local EXPORT_OPTIONS="$PROJECT_DIR/ios/ExportOptions.plist"

  if [[ ! -f "$EXPORT_OPTIONS" ]]; then
    warn "ios/ExportOptions.plist not found — creating a default template"
    cat > "$EXPORT_OPTIONS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>app-store</string>
  <!-- REQUIRED: set your 10-character Apple Team ID -->
  <key>teamID</key>
  <string>YOUR_TEAM_ID</string>
  <!-- REQUIRED: map bundle ID → provisioning profile name -->
  <key>provisioningProfiles</key>
  <dict>
    <key>$IOS_BUNDLE_ID</key>
    <string>YOUR_PROVISIONING_PROFILE_NAME</string>
  </dict>
  <key>uploadBitcode</key>
  <false/>
  <key>compileBitcode</key>
  <false/>
  <key>uploadSymbols</key>
  <true/>
</dict>
</plist>
PLIST
    warn "Created ios/ExportOptions.plist — you MUST edit teamID and provisioningProfiles before building."
  fi

  xcodebuild \
    -workspace "$PROJECT_DIR/ios/Runner.xcworkspace" \
    -scheme Runner \
    -configuration Release \
    -archivePath "$ARCHIVE_PATH" \
    archive

  xcodebuild \
    -exportArchive \
    -archivePath "$ARCHIVE_PATH" \
    -exportOptionsPlist "$EXPORT_OPTIONS" \
    -exportPath "$EXPORT_PATH"

  ok "IPA ready at $EXPORT_PATH"
}

# ═══════════════════════════════════════════════════════════════
#  BOTH
# ═══════════════════════════════════════════════════════════════

build_both_release() {
  build_android_release
  build_ios_ipa
}

# ═══════════════════════════════════════════════════════════════
#  MAIN LOOP
# ═══════════════════════════════════════════════════════════════

while true; do
  show_menu
  read -r choice
  case "$choice" in
    1) run_android_debug    ;;
    2) run_android_release  ;;
    3) build_android_release;;
    4) run_ios_debug        ;;
    5) run_ios_release      ;;
    6) build_ios_ipa        ;;
    7) build_both_release   ;;
    0) echo -e "\n  Bye!\n"; exit 0 ;;
    *) warn "Invalid option. Choose 0–7." ;;
  esac
  echo ""
  printf "  Press Enter to return to menu... "
  read -r
done