// lib/utils/localization.dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _vi = <String, String>{
  'appName': 'MoneyFlow',
  'appSubtitle': 'Quản lý tài chính thông minh',
  'signInApple': 'Đăng nhập với Apple',
  'signInGoogle': 'Đăng nhập với Google',
  'continueGuest': 'Tiếp tục không cần đăng nhập',
  'orLabel': 'hoặc',
  'balance': 'Số dư',
  'income': 'Thu nhập',
  'outcome': 'Chi tiêu',
  'expense': 'Chi tiêu',
  'all': 'Tất cả',
  'today': 'Hôm nay',
  'thisWeek': 'Tuần này',
  'thisMonth': 'Tháng này',
  'thisYear': 'Năm này',
  'addTransaction': 'Thêm giao dịch',
  'editTransaction': 'Sửa giao dịch',
  'deleteTransaction': 'Xóa giao dịch',
  'amount': 'Số tiền',
  'category': 'Danh mục',
  'note': 'Ghi chú',
  'date': 'Ngày',
  'receipt': 'Hóa đơn',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'edit': 'Sửa',
  'search': 'Tìm kiếm...',
  'noTransactions': 'Chưa có giao dịch nào',
  'addFirst': 'Nhấn + để thêm giao dịch đầu tiên',
  'camera': 'Máy ảnh',
  'photoLibrary': 'Thư viện ảnh',
  'removeReceipt': 'Xóa ảnh',
  'workingOffline': 'Đang hoạt động offline',
  'synced': 'Đã đồng bộ',
  'pending': 'Chờ đồng bộ',
  'settings': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'currency': 'Tiền tệ',
  'budget': 'Ngân sách',
  'categories': 'Danh mục',
  'appInfo': 'Thông tin ứng dụng',
  'signOut': 'Đăng xuất',
  'exitGuestMode': 'Thoát chế độ khách',
  'monthlyLimit': 'Hạn mức tháng',
  'yearlyLimit': 'Hạn mức năm',
  'reports': 'Báo cáo',
  'week': 'Tuần',
  'month': 'Tháng',
  'year': 'Năm',
  'netBalance': 'Số dư ròng',
  'avgDaily': 'TB/ngày',
  'noLimit': 'Chưa đặt hạn mức',
  'budgetWarning': 'Cảnh báo ngân sách',
  'budgetExceeded': 'Vượt ngân sách',
  'confirmDelete': 'Xác nhận xóa',
  'cannotUndo': 'Hành động này không thể hoàn tác.',
  'categoryManagement': 'Quản lý danh mục',
  'newCategory': 'Danh mục mới',
  'categoryName': 'Tên danh mục',
  'categoryType': 'Loại',
  'both': 'Cả hai',
  'defaultBadge': 'Mặc định',
  'cannotDeleteDefault': 'Không thể xóa danh mục mặc định.',
  'affectedTx': 'giao dịch sẽ bị ảnh hưởng.',
  'syncStatus': 'Trạng thái đồng bộ',
  'createdAt': 'Ngày tạo',
  'version': 'Phiên bản',
  'cloudSync': 'Đồng bộ đám mây',
  'allSynced': 'Tất cả đã đồng bộ',
  'pendingSync': 'mục chờ đồng bộ',
  'newestFirst': 'Mới nhất trước',
  'oldestFirst': 'Cũ nhất trước',
  'from': 'Từ',
  'to': 'Đến',
  'bar': 'Cột',
  'line': 'Đường',
  'pie': 'Tròn',
  'categoryBreakdown': 'Phân tích danh mục',
  'transactions': 'Giao dịch',
  'signOutConfirm': 'Bạn có chắc muốn đăng xuất?',
  'signOutWarn': 'Tất cả dữ liệu cục bộ sẽ bị xóa.',
  'guestMode': 'Chế độ khách',
  'errAmount': 'Vui lòng nhập số tiền lớn hơn 0',
  'errCategory': 'Vui lòng chọn danh mục',
  'iconPicker': 'Chọn biểu tượng',
  'colorPicker': 'Chọn màu',
  'preview': 'Xem trước',
};

const _en = <String, String>{
  'appName': 'MoneyFlow',
  'appSubtitle': 'Smart finance management',
  'signInApple': 'Sign in with Apple',
  'signInGoogle': 'Sign in with Google',
  'continueGuest': 'Continue as Guest',
  'orLabel': 'or',
  'balance': 'Balance',
  'income': 'Income',
  'outcome': 'Outcome',
  'expense': 'Expense',
  'all': 'All',
  'today': 'Today',
  'thisWeek': 'This Week',
  'thisMonth': 'This Month',
  'thisYear': 'This Year',
  'addTransaction': 'Add Transaction',
  'editTransaction': 'Edit Transaction',
  'deleteTransaction': 'Delete Transaction',
  'amount': 'Amount',
  'category': 'Category',
  'note': 'Note',
  'date': 'Date',
  'receipt': 'Receipt',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'search': 'Search...',
  'noTransactions': 'No transactions yet',
  'addFirst': 'Tap + to add your first transaction',
  'camera': 'Camera',
  'photoLibrary': 'Photo Library',
  'removeReceipt': 'Remove',
  'workingOffline': 'Working Offline',
  'synced': 'Synced',
  'pending': 'Pending sync',
  'settings': 'Settings',
  'language': 'Language',
  'currency': 'Currency',
  'budget': 'Budget',
  'categories': 'Categories',
  'appInfo': 'App Info',
  'signOut': 'Sign Out',
  'exitGuestMode': 'Exit Guest Mode',
  'monthlyLimit': 'Monthly Limit',
  'yearlyLimit': 'Yearly Limit',
  'reports': 'Reports',
  'week': 'Week',
  'month': 'Month',
  'year': 'Year',
  'netBalance': 'Net Balance',
  'avgDaily': 'Avg Daily',
  'noLimit': 'No limit set',
  'budgetWarning': 'Budget Warning',
  'budgetExceeded': 'Budget Exceeded',
  'confirmDelete': 'Confirm Delete',
  'cannotUndo': 'This action cannot be undone.',
  'categoryManagement': 'Category Management',
  'newCategory': 'New Category',
  'categoryName': 'Category Name',
  'categoryType': 'Type',
  'both': 'Both',
  'defaultBadge': 'Default',
  'cannotDeleteDefault': 'Default categories cannot be deleted.',
  'affectedTx': 'transactions will be affected.',
  'syncStatus': 'Sync Status',
  'createdAt': 'Created',
  'version': 'Version',
  'cloudSync': 'Cloud Sync',
  'allSynced': 'All data synced',
  'pendingSync': 'items pending sync',
  'newestFirst': 'Newest First',
  'oldestFirst': 'Oldest First',
  'from': 'From',
  'to': 'To',
  'bar': 'Bar',
  'line': 'Line',
  'pie': 'Pie',
  'categoryBreakdown': 'Category Breakdown',
  'transactions': 'Transactions',
  'signOutConfirm': 'Are you sure you want to sign out?',
  'signOutWarn': 'All local data will be cleared.',
  'guestMode': 'Guest Mode',
  'errAmount': 'Please enter an amount greater than 0',
  'errCategory': 'Please select a category',
  'iconPicker': 'Choose Icon',
  'colorPicker': 'Choose Color',
  'preview': 'Preview',
};

class LocalizationProvider extends ChangeNotifier {
  String _language = 'vi';
  String get language => _language;

  LocalizationProvider() { _load(); }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    final v = prefs.getString('app_language');
    if (v != null) { _language = v; notifyListeners(); }
  }

  Future<void> setLanguage(String lang) async {
    _language = lang;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', lang);
  }

  String str(String key) {
    final table = _language == 'vi' ? _vi : _en;
    return table[key] ?? _en[key] ?? key;
  }
}